- type: cargoProduct
  id: SecurityCombatGloves
  icon:
    sprite: Clothing/Hands/Gloves/combat.rsi
    state: icon
  product: CrateSecurityCombatGloves
  cost: 5500
  category: cargoproduct-category-name-security
  group: market
